codeserver:
  container_name: codeserver
  image: "lscr.io/linuxserver/code-server:latest"
  port: 8443
  ssh_port: 2222
  memory: "512m"
  memory_swap: "1g"
  cpus: 0.5
  puid: "1024"
  pgid: "100"
  timezone: "UTC"
