# Docker network
docker_network_name: synology_net
docker_network_subnet: 172.25.0.0/16
docker_data_path: /volume1/docker

# Global defaults
default_timezone: Europe/Amsterdam
default_puid: "1024"
default_pgid: "100"
