# Ansible settings
ansible_python_interpreter: /opt/bin/python3

# Code Server
codeserver:
  ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIGvHZGln74hveFbkxovy/S2NSpdeNnqSfHgssh+KRDn"
  container_name: codeserver
  image: "lscr.io/linuxserver/code-server:latest"
  password: "{{ vault_codeserver_password }}"
  sudo_password: "{{ vault_codeserver_password }}"
  port: 8443
  ssh_port: 2222
  memory: "512m"
  memory_swap: "1g"
  puid: "1024"
  pgid: "100"
  timezone: "Europe/Amsterdam"

# MariaDB
mariadb:
  container_name: mariadb
  image: "mariadb:11"
  root_password: "{{ vault_mariadb_root_password }}"
  user: "nextcloud"
  user_password: "{{ vault_mariadb_user_password }}"
  database: "nextcloud"
  memory: "512m"
  memory_swap: "1g"

# Nextcloud
nextcloud:
  container_name: nextcloud
  image: "lscr.io/linuxserver/nextcloud:latest"
  db_password: "{{ vault_mariadb_user_password }}"
  db_user: "nextcloud"
  database: "nextcloud"
  port: 6001  
  memory: "1024m"
  memory_swap: "2g"
  puid: "1024"
  pgid: "100"
  timezone: "Europe/Amsterdam"

# Redis
redis:
  container_name: redis
  image: "redis:7"
  memory: "256m"
  memory_swap: "512m"
